{
	//init create all the obj
	"initial": [
        {"obj": "rs232","class": "COMMON.rs232_interface_monopoly_proxy.RS232"}
	],

	"monopoly":[
	    {"obj": "rs232","class": "COMMON.rs232_interface_monopoly.RS232","COM":"COM4"}
	],

	"locks":[
	    {"name":"lock1"},
	    {"name":"lock2"},
	    {"name":"lockForSomething"}
	],

	"barriers":[
	    {"name":"barrier1"},
	    {"name":"barrier2"},
	    {"name":"barrier3"},
	    {"name":"barrierForSomething"}
	],

	"process":[
	    {"name":"CONNECT","obj" : "rs232","action": "askmonopoly","do":"connect","barrier":"barrier1"},

	    {"name":"TEST_BARRIER1_LIKE_FIXTUREIN","obj" : "rs232","action": "askmonopoly","do":"sendCmd",
            "cmd":"fixture in\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

	    {"name":"TEST_LOCK1","obj" : "rs232","action": "askmonopoly","do":"sendCmd",
            "cmd":"root\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

	    {"name":"TEST_LOCK2","obj" : "rs232","action": "askmonopoly","do":"sendCmd",
            "cmd":"root\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

	    {"name":"TEST_BARRIER2_LIKE_POWERON","obj" : "rs232","action": "askmonopoly","do":"sendCmd",
            "cmd":"poweron\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

	    {"name":"TEST_LOCK3","obj" : "rs232","action": "askmonopoly","do":"sendCmd",
            "cmd":"root\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

        {"name":"TEST_LOCK3","obj" : "rs232","action": "askmonopoly","do":"sendCmd",
            "cmd":"root\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

        {"name":"TEST_LOCK3","obj" : "rs232","action": "askmonopoly","do":"sendCmd",
            "cmd":"root\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

        {"name":"TEST_FAKE","obj" : "rs232","action": "fakeitem",
            "cmd":"root\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

	    {"name":"TEST_BARRIER3_LIKE_FIXTUROUT","obj" : "rs232","action": "askmonopoly","do":"sendCmd",
            "cmd":"fixture out\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

        {"name":"DISCONNECT","obj" : "rs232","action": "askmonopoly","do":"disconnect","barrier":"barrier1"}
	]
}