{
	//init create all the obj
	"initial": [
	    {"obj": "basic_info","class": "COMMON.basic_info.BasicInfo"},
	    {"obj": "dialog","class": "COMMON.dialog.dialog"},
		{"obj": "sfis","class": "SFIS.SFIS.SFIS"}
	],

	"locks":[
	    {"name":"lockSFIS"}
	],

	"barriers":[
	    {"name":"barrier1"},
	    {"name":"barrier2"},
	    {"name":"barrier3"},
	    {"name":"barrierForSomething"}
	],

	"process":[
	    {"name":"TEST_DIALOG","obj" : "dialog","action": "info"},
	    {"name":"TEST_DIALOG","obj" : "dialog","action": "yesorno"},
	    {"name":"TEST_DIALOG","obj" : "dialog","action": "ledForM1"}
	]
}