{
	//init create all the obj
	"initial": [
		{"obj": "rs232","class": "COMMON.rs232_interface.RS232","COM":"/dev/tty.usbmodem1412"}
	],

	"locks":[
	    {"name":"lock1"},
	    {"name":"lock2"},
	    {"name":"lockForSomething"}
	],

	"barriers":[
	    {"name":"barrier1"},
	    {"name":"barrier2"},
	    {"name":"barrier3"},
	    {"name":"barrierForSomething"}
	],

	"process":[
	    {"name":"CONNECT","obj" : "rs232","action": "connect","lock":"lock1"},

	    {"name":"TEST_BARRIER1_LIKE_FIXTUREIN","obj" : "rs232","action": "sendCmd",
            "cmd":"fixture in\r","end":"# ","has":"#","timeout":"1","barrier":"barrier1"},

	    {"name":"TEST_LOCK1","obj" : "rs232","action": "sendCmd",
            "cmd":"root\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

	    {"name":"TEST_LOCK2","obj" : "rs232","action": "sendCmd",
            "cmd":"root\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

	    {"name":"TEST_BARRIER2_LIKE_POWERON","obj" : "rs232","action": "sendCmd",
            "cmd":"poweron\r","end":"# ","has":"#","timeout":"1","barrier":"barrier2"},

	    {"name":"TEST_LOCK3","obj" : "rs232","action": "sendCmd",
            "cmd":"root\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

        {"name":"TEST_LOCK3","obj" : "rs232","action": "sendCmd",
            "cmd":"root\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

        {"name":"TEST_LOCK3","obj" : "rs232","action": "sendCmd",
            "cmd":"root\r","end":"# ","has":"#","timeout":"1","lock":"lock1"},

	    {"name":"TEST_BARRIER3_LIKE_FIXTUROUT","obj" : "rs232","action": "sendCmd",
            "cmd":"fixture out\r","end":"# ","has":"#","timeout":"1","barrier":"barrier3"}
	]
}